### ISSUE TITLE
checkNameSpaceConflicts for deeply nested query with repeated verb names

### ISSUE THREAD

**Issue by Hades32** [product-os/jellyfish#7381]
This error
```
REQUEST-39.2.6-64818319-10a7-4138-9471-fe189cebe376]: HTTP unexpected error {"name":"error","message":"table name \"links@/has attached commit.0/was built into.0/was built into.0/\" specified more than once","stack":"error: table name \"links@/has attached commit.0/was built into.0/was built into.0/\" specified more than once\n    at Parser.parseErrorMessage (/usr/src/jellyfish/apps/server/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/usr/src/jellyfish/apps/server/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/usr/src/jellyfish/apps/server/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/usr/src/jellyfish/apps/server/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (events.js:400:28)\n    at Socket.emit (domain.js:475:12)\n    at addChunk (internal/streams/readable.js:293:12)\n    at readableAddChunk (internal/streams/readable.js:267:9)\n    at Socket.Readable.push (internal/streams/readable.js:206:10)\n    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)\n    at TCP.callbackTrampoline (internal/async_hooks.js:130:17)","length":177,"severity":"ERROR","code":"42712","file":"parse_relation.c","line":"423","routine":"checkNameSpaceConflicts"}
```
happens when I try to execute this query
```javascript
let prs = await sdk.query({
    type: 'object',
    properties: {
        type: {
            const: 'pull-request@1.0.0'
        }
    },
    anyOf: [true, {
            $$links: {
                "has attached commit": {
                    type: 'object',
                    anyOf: [true, {
                            $$links: {
                                "was built into": {
                                    type: 'object',
                                    anyOf: [true, {
                                            $$links: {
                                                "was built into": {
                                                    type: 'object',
                                                    anyOf: [true, {
                                                            $$links: {
                                                                "was built into": true
                                                            }
                                                        }, {
                                                            $$links: {
                                                                "was merged as": true
                                                            }
                                                        }
                                                    ]
                                                }
                                            }
                                        }, {
                                            $$links: {
                                                "was merged as": true
                                            }
                                        }
                                    ]
                                }
                            }
                        }, {
                            $$links: {
                                "has attached check run": true
                            }
                        }
                    ]
                }
            }
        }
    ]
}, {
    limit: 10,
    sortBy: 'updated_at',
    sortDir: 'desc'
});
prs
```
but not with this slightly simplified version
```javascript
let prs = await sdk.query({
    type: 'object',
    properties: {
        type: {
            const: 'pull-request@1.0.0'
        }
    },
    anyOf: [true, {
            $$links: {
                "has attached commit": {
                    type: 'object',
                    anyOf: [true, {
                            $$links: {
                                "was built into": {
                                    type: 'object',
                                    anyOf: [true, {
                                            $$links: {
                                                "was built into": true
                                            }
                                        }, {
                                            $$links: {
                                                "was merged as": true
                                            }
                                        }
                                    ]
                                }
                            }
                        }, {
                            $$links: {
                                "has attached check run": true
                            }
                        }
                    ]
                }
            }
        }
    ]
}, {
    limit: 10,
    sortBy: 'updated_at',
    sortDir: 'desc'
});
prs
```

**Comment by Ereski** [comment]
For reference the solution here is to prepend a short, unique ID to these identifiers.
